/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package python;

/**
 *
 * @author ALUNO
 */
public class Fucaoleiapython extends javax.swing.JFrame {

    /**
     * Creates new form Fucaoleiapython
     */
    public Fucaoleiapython() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 610, -1, -1));

        jTextArea2.setColumns(20);
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setText("Em python, para ler dados digitados pelo usuário durante a execução do programa, utilizamos a função input() (literalmente entrada, em inglês). O exemplo abaixo ilustra o uso dessa função:\n\nprint(\"Digite seu nome:\")\nnome = input()\nprint(\"Bem-vindo, \", nome)\nDigite seu nome:\nAlgoritmos em Python\nBem-vindo,  Algoritmos em Pyhon\nUm detalhe importante a ser lembrado é que a função input() sempre lê strings. Por isso, caso você deseje ler um número, deverá converter o dado retornado por essa função para o formato numérico apropriado.\n\nOutra opção (mais eficiente) para leitura de dados é usar a função readline(). Suponha que queiramos ler dois números inteiros, representando a idade e o peso (arredondado) de uma pessoa. Um exemplo desse tipo de dado seria o seguinte:\n\n45 70\nPara ler esses dois valores (como inteiros) em Python, podemos fazer o seguinte:\n\nimport sys\n\nidade, peso = map(int, sys.stdin.readline().split())\nEsse tipo de leitura de dados é bastante útil quando estamos lidando com dados que obedecem um formato específico. No código acima, o que fazemos é mapear cada um dos elementos lidos para o tipo int.\n\nLeitura de Dados de Arquivos\nÉ possível também ler dados diretamente de um arquivo em Python. Por exemplo, considere que tenhamos um arquivo de texto chamado arquivo.txt em nosso computador (no mesmo diretório que nosso programa Python) com o seguinte conteúdo:\n\nSujeito de sorte (Belchior):\nPresentemente eu posso me considerar um sujeito de sorte\nPorque apesar de muito moço me sinto são e salvo e forte\nE tenho comigo pensado Deus é brasileiro e anda do meu lado\nE assim já não posso sofrer no ano passado");
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 620, 450));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Função Leia ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/python/img/PYTHON.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Botão sair
        
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fucaoleiapython.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fucaoleiapython.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fucaoleiapython.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fucaoleiapython.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fucaoleiapython().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
